### ISSUE TITLE
Default configuration autoreload results in problem report in OS X Lion.

### ISSUE THREAD

**Issue by yesimon** [rfk/django-supervisor#24]
When running `./manage.py supervisor` with an empty `supervisord.conf`, only the autoreload program is running. When I save a file and the reloader process reloaded, the OS X crash reporter pops up saying 'Python quit unexpectedly'. The stack trace is not super helpful. In the short term, I can work around this by disabling the OS X problem reporter.

Thread 0 Crashed:
0   com.apple.CoreFoundation        0x00007fff845878e6 CFRunLoopWakeUp + 150
1   _watchdog_fsevents.so           0x00000001013ea915 watchdog_stop + 37
2   org.python.python               0x00000001000a3ed1 PyEval_EvalFrameEx + 6657
3   org.python.python               0x00000001000a2479 PyEval_EvalCodeEx + 2201
4   org.python.python               0x00000001000aa2b9 fast_function + 313
5   org.python.python               0x00000001000a417e PyEval_EvalFrameEx + 7342
6   org.python.python               0x00000001000aa243 fast_function + 195

System setup:

OS X 10.7
Python 2.7.3 (installed with homebrew as framework `brew install python --framework`)
Django==1.4
django-supervisor==0.3.0
watchdog==0.6.0

Mainly I'd be interested if anybody else can reproduce this bug, and it might actually be a watchdog bug.

**Comment by rfk** [comment]
Thanks for reaching out. Unfortunately I am no longer actively maintaining this project, so I'm going to move it into archive mode:

  https://rfk.id.au/blog/entry/archiving-open-source-projects/
