### ISSUE TITLE
Support for per-app config files removed with no option to turn it back on and no warning or version number change.

### ISSUE THREAD

**Issue by dragonpaw** [rfk/django-supervisor#25]
It seems like you removed support for per-app config files recently. Unfortunately this quite broke things for us. If you don't want this to be default behavior, it would be nice if there were at least a config setting we could put in supervisord.conf or on the command line to turn it back on. We had no problem at all with this setup, and were quite surprised when it vanished without warning.

Alternatively, at least bump the version number when this happens, so our requirement.txt files can be set to require the older version (unfortunately there are now two versions of 0.3.0 in the wild, one with support for per-app configs, one without) and possibly do a little loop through all the apps to see if any have config files in them and print a warning that this is no longer supported. (Would have saved us half a day of troubleshooting to figure out why two machines with the exact same version (0.3.0) had wildly different behaviors.

**Comment by rfk** [comment]
Thanks for reaching out. Unfortunately I am no longer actively maintaining this project, so I'm going to move it into archive mode:

  https://rfk.id.au/blog/entry/archiving-open-source-projects/
