### ISSUE TITLE
Running multiple gunicorn commands ignores different settings

### ISSUE THREAD

**Issue by tspecht** [rfk/django-supervisor#32]
Hello folks,

I'm currently trying to launch multiple gunicorn instances via django-supervisor each having a custom settings file to have them use different databases. Everything works quite well expect the calls to gunicorn which I encapsulated in different programs seem to ignore the separate settings file I specified .... Any hints?

[program:webserver_first]
command=gunicorn -w 2 myApp.wsgi:application --settings myApp.settings_prod -b 127.0.0.1:8027

[program:webserver_second]
command=gunicorn -w 2 myApp.wsgi:application --settings myApp.settings_prod_second -b 127.0.0.1:4020

**Comment by rfk** [comment]
Thanks for reaching out. Unfortunately I am no longer actively maintaining this project, so I'm going to move it into archive mode:

  https://rfk.id.au/blog/entry/archiving-open-source-projects/
