### ISSUE TITLE
"include" section with relative file path(s) is silently ignored

### ISSUE THREAD

**Issue by blueyed** [rfk/django-supervisor#35]
When using the following in apps/supervisord.conf, which is used by django-supervisor, the referenced include file is silently ignored:

```
[include]
files = ../supervisord.conf
```

I guess that this is caused by the config being passed as a string:

```
    cfg_file = OnDemandStringIO(get_merged_config, **options)
    #  With no arguments, we launch the processes under supervisord.
    if not args:
        return supervisord.main(("-c",cfg_file))
```

And supervisor appears to silently ignore any non-existent "files" in the "include" section.

Using an absolute path works around this.

**Comment by rfk** [comment]
Thanks for reaching out. Unfortunately I am no longer actively maintaining this project, so I'm going to move it into archive mode:

  https://rfk.id.au/blog/entry/archiving-open-source-projects/
