### ISSUE TITLE
Python 3 Support

### ISSUE THREAD

**Issue by mnaberez** [rfk/django-supervisor#36]
Django supports Python 2 and 3 since version 1.5.  Supervisor does not yet have a release version that supports Python 3, but there is a branch that supports Python 2 and 3 that is planned to be the next major version.  It is not complete yet but the tests pass and it works for the most part.  

According to the classifiers in setup.py, django-supervisor only supports Python 2.  Now is a great time to think about a version of django-supervisor that supports Python 2 and 3.

**Comment by NDevox** [comment]
@mnaberez do we know what the progress is with this? it's been 2 years and doesn't look like much has changed. Where is the branch you mentioned?
