### ISSUE TITLE
autoreloader should handle case of no autoreload programs

### ISSUE THREAD

**Issue by blueyed** [rfk/django-supervisor#38]
With no autoreload programs, the autoreload process results in:

```
2014-03-24 03:39:04,887 DEBG 'autoreload' stdout output:
Error: restart requires a process name
restart <name>      Restart a process
restart <gname>:*   Restart all processes in a group
restart <name> <name>   Restart multiple processes or groups
restart all     Restart all processes
Note: restart does not reread config files. For that, see reread and update.
```

If `_get_autoreload_programs` returns an empty list, a warning/info should get logged (maybe only once) and no restart should get initiated.

I was not sure how to implement this, since django-supervisor does not use any logging currently.
Should this get done via `print()`, or should a `logger = logging.getLogger(__name__)`-like logger be used?

**Comment by rfk** [comment]
Thanks for reaching out. Unfortunately I am no longer actively maintaining this project, so I'm going to move it into archive mode:

  https://rfk.id.au/blog/entry/archiving-open-source-projects/
