### ISSUE TITLE
running stop all from shell on OSX Lion holds HTTP port

### ISSUE THREAD

**Issue by professorDante** [rfk/django-supervisor#41]
python manage.py supervisor --daemonize runs fine. Stop all the processes by issuing stop all command in the shell, then try to run python manage.py supervisor, and it fails with:
Error: Another program is already listening on a port that one of our HTTP servers is configured to use.  Shut this program down first before starting supervisord.

**Comment by rfk** [comment]
Thanks for reaching out. Unfortunately I am no longer actively maintaining this project, so I'm going to move it into archive mode:

  https://rfk.id.au/blog/entry/archiving-open-source-projects/
