### ISSUE TITLE
Use a different name than `supervisor.conf`.

### ISSUE THREAD

**Issue by mrmachine** [rfk/django-supervisor#45]
It's not a supervisor config file, it's a supervisor config file template.

When you run `supervisorctl`, it will use the `supervisor.conf` file from the current working directory if there is one. We use a system level supervisor to start our apps which use `django-supervisor`.

This means that if we try to control the system level supervisor while in the app directory, it fails with some errors about our bogus configuration, because it's trying to read the Django template.

This should at least be configurable, so we can name the file something like `supervisor.conf.tmpl` or `supervisor.conf`, so we won't be forever typing `cd ..` before `sudo supervisorctl ...` :)

Ideally though, it should probably just try to read `supervisor.conf.tmpl` first, and fallback to `supervisor.conf` (with a deprecation warning)?

**Comment by alexsilva** [comment]
Look this https://github.com/rfk/django-supervisor/blob/master/djsupervisor/config.py#L30

**Comment by mrmachine** [comment]
Awesome. This should be mentioned in the docs/README.

**Comment by rfk** [comment]
Thanks for reaching out. Unfortunately I am no longer actively maintaining this project, so I'm going to move it into archive mode:

  https://rfk.id.au/blog/entry/archiving-open-source-projects/
