### ISSUE TITLE
Cyclic import triggered with django 1.9

### ISSUE THREAD

**Issue by philpep** [rfk/django-supervisor#48]
Hi,

I use django-supervisor 0.3.3 and have this issue while trying to upgrade from django 1.8 to django 1.9:

```
InvalidTemplateLibrary: Invalid template library specified. ImportError raised when trying to load 'djsupervisor.templatetags.djsupervisor_tags': cannot import name djsupervisor_tags
```

After investigating a bit, it's seem that's because of a cyclic import:

```
>>> import djsupervisor.templatetags.djsupervisor_tags
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/phil/venvs/mca-5c2e50c/local/lib/python2.7/site-packages/djsupervisor/templatetags/djsupervisor_tags.py", line 17, in <module>
    import djsupervisor.config
  File "/home/phil/venvs/mca-5c2e50c/local/lib/python2.7/site-packages/djsupervisor/config.py", line 28, in <module>
    from djsupervisor.templatetags import djsupervisor_tags
ImportError: cannot import name djsupervisor_tags
```

So `djsupervisor.templatetags.djsupervisor_tags` import `djsupervisor.config` which import `djsupervisor.templatetags.djsupervisor_tags`.

Cannot explain why this bug doesn't occur with django 1.8...

Thanks.

**Comment by rfk** [comment]
This should be fixed in v0.3.4, thanks to https://github.com/rfk/django-supervisor/pull/49
