### ISSUE TITLE
Is there a way to start process only when it's not started yet?

### ISSUE THREAD

**Issue by jasjuang** [rfk/django-supervisor#52]
For the first time deploying, I cam simply do 

```
python manage.py supervisor -d
```

If I deploy for the second time I will get an 

```
Error: Another program is already listening on a port that one of our HTTP servers is configured to use.  Shut this program down first before starting supervisord.
```

So I have to do

```
python manage.py supervisor shutdown
python manage.py supervisor -d
```

But then if this is deployed to a new instance then I get 

```
ERROR: http://127.0.0.1:9544 refused connection (already shut down?)
```

Is there a command that starts the process only when it's not started and not return an error message?

**Comment by rfk** [comment]
Thanks for reaching out. Unfortunately I am no longer actively maintaining this project, so I'm going to move it into archive mode:

  https://rfk.id.au/blog/entry/archiving-open-source-projects/
