### ISSUE TITLE
hao to configure celery mult in django-supervisor

### ISSUE THREAD

**Issue by zhangjianpinghik** [rfk/django-supervisor#53]
for exzample : the celery mult is:
celery multi start 4 -c 10 -A digger -Q analyse_report_queue -P eventlet -l info --pidfile="/tmp/celery/analyse_report_%n.pid" --logfile="var/log/celery/analyse_report_%n.log"

how to make the above celery mult command in the django supervisord.conf?

**Comment by rfk** [comment]
Thanks for reaching out. Unfortunately I am no longer actively maintaining this project, so I'm going to move it into archive mode:

  https://rfk.id.au/blog/entry/archiving-open-source-projects/
