### ISSUE TITLE
django-supervisor 0.4.0 and supervisor 3.3.1 KeyError: 'ctl-command'

### ISSUE THREAD

**Issue by alanrhannah** [rfk/django-supervisor#54]
django-supervisor 0.4.0 and supervisor 3.3.1 raises `KeyError: 'ctl-command'` when trying to launch / daemonize supervisor via `./manage.py supervisor --daemonize`

Currently running django version 1.5

Please let me know what info you require to debug.

**Comment by alanrhannah** [comment]
I should also add that supervisor 3.3.1 and django-supervisor 0.3.4 work together fine.

**Comment by rfk** [comment]
Thanks for reaching out. Unfortunately I am no longer actively maintaining this project, so I'm going to move it into archive mode:

  https://rfk.id.au/blog/entry/archiving-open-source-projects/
