### ISSUE TITLE
Python3 support

### ISSUE THREAD

**Issue by jlariza** [rfk/django-supervisor#55]
Hello

Is there any plans of support python3?

Thank you

**Comment by thijstriemstra** [comment]
Without any tests this will be hard to do/verify.

**Comment by DragosChirila** [comment]
I got it working on python 3.6 with these small fixes - https://github.com/DragosChirila/django-supervisor/commit/07c67b4daebe4ebae5eb1c5567c11e076e58692d

**Comment by rfk** [comment]
Thanks for reaching out. Unfortunately I am no longer actively maintaining this project, so I'm going to move it into archive mode:

  https://rfk.id.au/blog/entry/archiving-open-source-projects/
