### ISSUE TITLE
Stuck waiting for celeryd to die

### ISSUE THREAD

**Issue by lsemel** [rfk/django-supervisor#7]
Whenever I try to shut down supervisor, it endlessly prints a message like this:

'2011-06-24 19:10:04,916 INFO waiting for celeryd to die'

Any ideas what could be causing celeryd to fail to exit or how to diagnose the problem?  I have to kill the processes manually in order for supervisor to quit.

Lee

**Comment by rfk** [comment]
Thanks for reaching out. Unfortunately I am no longer actively maintaining this project, so I'm going to move it into archive mode:

  https://rfk.id.au/blog/entry/archiving-open-source-projects/
