### ISSUE TITLE
Example - how to start django-supervisor automatically on Ubuntu using upstart

### ISSUE THREAD

**Issue by lsemel** [rfk/django-supervisor#8]
Here's how I set up django-supervisor to execute when my VPS boots up.  This file goes in `/etc/init/django-supervisor.conf`.  Any output or errors from this file itself will appear in `/var/log/test.debug` since Upstart is apparently bad about outputting errors.

```
description     "start django-supervisor"

start on runlevel [2345]
stop on runlevel [!2345]
env RUN_AS_USER=root
env VIRTUALENV=myvirtualenv
env PROJECT_DIR=/home/www/myprojectdir
env CMD="source /opt/virtualenvs/$VIRTUALENV/bin/activate; /usr/bin/env python $PROJECT_DIR/manage.py supervisor"

respawn
script
    exec >/var/log/test.debug 2>&1
    echo $CMD
    cd $PROJECT_DIR
    su -c "$CMD" $RUN_AS_USER
end script
```

If you'd like I can add this to the README or other docs.

**Comment by rfk** [comment]
Thanks for reaching out. Unfortunately I am no longer actively maintaining this project, so I'm going to move it into archive mode:

  https://rfk.id.au/blog/entry/archiving-open-source-projects/
